api_version: 1.0

rmp_params:
    step_size: 0.01667

target_rmp:
    metric_scalar: 1.0
    gain_damping: 50.0
    gain_position: 100.0
    inertia: 1.0

axis_target_rmp:
    metric_scalar: 1.0
    gain_damping: 50.0
    gain_position: 100.0
    inertia: 1.0

joint_limit_rmp:
    metric_scalar: 1.0
    gain_damping: 30.0
    gain_repulsion: 10.0
    inertia: 1.0

joint_velocity_cap_rmp:
    metric_scalar: 1.0
    gain_damping: 1.0
    gain_repulsion: 1.0
    inertia: 1.0
    max_velocity: 1.0

damper_rmp:
    metric_scalar: 1.0
    gain_damping: 1.0
    inertia: 1.0
